In [58]:
from empiricaldist import Pmf

In [59]:
coin = Pmf()
coin['heads'] = 1/2
coin['tails'] = 1/2
coin

heads    0.5
tails    0.5
dtype: float64

In [60]:
die = Pmf.from_seq([1,2,3,4,5,6])
die

1    0.166667
2    0.166667
3    0.166667
4    0.166667
5    0.166667
6    0.166667
Name: proportion, dtype: float64

In [61]:
letters = Pmf.from_seq(list(('Malaka')))
letters

M    0.166667
a    0.500000
k    0.166667
l    0.166667
Name: proportion, dtype: float64

In [62]:
letters('t')

0

In [63]:
letters('M')

0.16666666666666666

In [64]:
die([1, 3, 8])

array([0.16666667, 0.16666667, 0.        ])

# The Cookie Problem Revisited

In [65]:
prior = Pmf.from_seq(['Bowl1', 'Bowl2'])
prior

Bowl1    0.5
Bowl2    0.5
Name: proportion, dtype: float64

In [66]:
likelihood_vanila = [0.75, 0.5]
posterior = prior * likelihood_vanila
posterior 

Bowl1    0.375
Bowl2    0.250
Name: proportion, dtype: float64

In [67]:
posterior.normalize()


0.625

In [68]:
posterior

Bowl1    0.6
Bowl2    0.4
Name: proportion, dtype: float64

In [69]:
posterior('Bowl1')

0.6

In [70]:
posterior *= likelihood_vanila
posterior.normalize()
posterior

Bowl1    0.692308
Bowl2    0.307692
Name: proportion, dtype: float64

In [71]:
likelihood_chocolate = [0.25, 0.5]

In [72]:
posterior *= likelihood_chocolate
posterior.normalize()
posterior

Bowl1    0.529412
Bowl2    0.470588
Name: proportion, dtype: float64

# 101 Bowls

In [73]:
import numpy as np

In [74]:
hypos = np.arange(101)

In [75]:
prior = Pmf(1, hypos)
prior.normalize()


101

In [76]:
prior.head()

0    0.009901
1    0.009901
2    0.009901
dtype: float64

In [77]:
likelihood_vanila = hypos / 100
likelihood_vanila[:5]

array([0.  , 0.01, 0.02, 0.03, 0.04])

In [78]:
posterior1 = prior * likelihood_vanila
posterior1.normalize()
posterior1.head(10)

0    0.000000
1    0.000198
2    0.000396
3    0.000594
4    0.000792
5    0.000990
6    0.001188
7    0.001386
8    0.001584
9    0.001782
dtype: float64

In [79]:
posterior1.tail()

98     0.019406
99     0.019604
100    0.019802
dtype: float64

In [80]:
posterior2 = posterior1 * likelihood_vanila
posterior2.normalize()

0.6699999999999999

In [81]:
likelihood_chocolate = 1 - hypos/100
posterior3 = posterior2 * likelihood_chocolate
posterior3.normalize()

0.2462686567164179

In [82]:
posterior3.idxmax()

67

In [83]:
posterior3.max_prob()

67

# The Dice Problem

### 1st roll revealed 1

In [84]:
hypos = [6, 8, 12]

In [85]:
prior = Pmf(1/3, hypos)
prior

6     0.333333
8     0.333333
12    0.333333
dtype: float64

In [86]:
prior.ps

array([0.33333333, 0.33333333, 0.33333333])

In [87]:
prior.qs

array([ 6,  8, 12])

In [88]:
likelihood = 1/6, 1/8, 1/12

In [89]:
posterior = prior * likelihood
posterior.normalize()
posterior

6     0.444444
8     0.333333
12    0.222222
dtype: float64

In [90]:
from fractions import Fraction

In [91]:
a = Fraction(1, 3)
a

Fraction(1, 3)

### 2nd roll shows "7"

In [92]:
likelihood2 = 0, 1/8, 1/12

In [93]:
posterior *= likelihood2
posterior.normalize()
posterior

6     0.000000
8     0.692308
12    0.307692
dtype: float64

# Updating Dice

In [94]:
def update_dice(pmf, data):
    """ Update Pmf based on new data"""
    hypos = pmf.qs
    likelihood = 1/hypos
    impossible = (data > hypos)
    likelihood[impossible] = 0
    pmf *= likelihood
    pmf.normalize()

In [95]:
pmf = prior.copy()
pmf

6     0.333333
8     0.333333
12    0.333333
dtype: float64

In [96]:
update_dice(pmf, 1)
update_dice(pmf, 7)
pmf

6     0.000000
8     0.692308
12    0.307692
dtype: float64

# Exercise 3-1

In [97]:
update_dice(pmf, 1)
update_dice(pmf, 3)
update_dice(pmf, 5)
update_dice(pmf, 7)
pmf

6     0.000000
8     0.919294
12    0.080706
dtype: float64

# Exercise 3-2

In [98]:
hypos = [4, 6, 8, 12, 20]

In [100]:
prior = Pmf(1/5, hypos)

In [101]:
prior

4     0.2
6     0.2
8     0.2
12    0.2
20    0.2
dtype: float64

In [102]:
update_dice(prior, 1)

In [103]:
prior

4     0.370370
6     0.246914
8     0.185185
12    0.123457
20    0.074074
dtype: float64