In [3]:
from empiricaldist import Pmf

In [4]:
coin = Pmf()
coin['heads'] = 1/2
coin['tails'] = 1/2
coin

heads    0.5
tails    0.5
dtype: float64

In [5]:
die = Pmf.from_seq([1,2,3,4,5,6])
die

1    0.166667
2    0.166667
3    0.166667
4    0.166667
5    0.166667
6    0.166667
Name: proportion, dtype: float64

In [6]:
letters = Pmf.from_seq(list(('Malaka')))
letters

M    0.166667
a    0.500000
k    0.166667
l    0.166667
Name: proportion, dtype: float64

In [7]:
letters('t')

0

In [8]:
letters('M')

0.16666666666666666

In [9]:
die([1, 3, 8])

array([0.16666667, 0.16666667, 0.        ])

# The Cookie Problem Revisited

In [10]:
prior = Pmf.from_seq(['Bowl1', 'Bowl2'])
prior

Bowl1    0.5
Bowl2    0.5
Name: proportion, dtype: float64

In [11]:
likelihood_vanila = [0.75, 0.5]
posterior = prior * likelihood_vanila
posterior 

Bowl1    0.375
Bowl2    0.250
Name: proportion, dtype: float64

In [12]:
posterior.normalize()


0.625

In [13]:
posterior

Bowl1    0.6
Bowl2    0.4
Name: proportion, dtype: float64

In [14]:
posterior('Bowl1')

0.6

In [15]:
posterior *= likelihood_vanila
posterior.normalize()
posterior

Bowl1    0.692308
Bowl2    0.307692
Name: proportion, dtype: float64

In [16]:
likelihood_chocolate = [0.25, 0.5]

In [17]:
posterior *= likelihood_chocolate
posterior.normalize()
posterior

Bowl1    0.529412
Bowl2    0.470588
Name: proportion, dtype: float64

# 101 Bowls

In [18]:
import numpy as np

In [19]:
hypos = np.arange(101)

In [20]:
prior = Pmf(1, hypos)
prior.normalize()


101

In [21]:
prior.head()

0    0.009901
1    0.009901
2    0.009901
dtype: float64

In [22]:
likelihood_vanila = hypos / 100
likelihood_vanila[:5]

array([0.  , 0.01, 0.02, 0.03, 0.04])

In [23]:
posterior1 = prior * likelihood_vanila
posterior1.normalize()
posterior1.head(10)

0    0.000000
1    0.000198
2    0.000396
3    0.000594
4    0.000792
5    0.000990
6    0.001188
7    0.001386
8    0.001584
9    0.001782
dtype: float64

In [24]:
posterior1.tail()

98     0.019406
99     0.019604
100    0.019802
dtype: float64

In [25]:
posterior2 = posterior1 * likelihood_vanila
posterior2.normalize()

0.6699999999999999

In [26]:
likelihood_chocolate = 1 - hypos/100
posterior3 = posterior2 * likelihood_chocolate
posterior3.normalize()

0.2462686567164179

In [27]:
posterior3.idxmax()

67

In [28]:
posterior3.max_prob()

67

# The Dice Problem

### 1st roll revealed 1

In [29]:
hypos = [6, 8, 12]

In [30]:
prior = Pmf(1/3, hypos)
prior

6     0.333333
8     0.333333
12    0.333333
dtype: float64

In [31]:
prior.ps

array([0.33333333, 0.33333333, 0.33333333])

In [32]:
prior.qs

array([ 6,  8, 12])

In [33]:
likelihood = 1/6, 1/8, 1/12

In [34]:
posterior = prior * likelihood
posterior.normalize()
posterior

6     0.444444
8     0.333333
12    0.222222
dtype: float64

In [35]:
from fractions import Fraction

In [36]:
a = Fraction(1, 3)
a

Fraction(1, 3)

### 2nd roll shows "7"

In [37]:
likelihood2 = 0, 1/8, 1/12

In [38]:
posterior *= likelihood2
posterior.normalize()
posterior

6     0.000000
8     0.692308
12    0.307692
dtype: float64

# Updating Dice

In [39]:
def update_dice(pmf, data):
    """ Update Pmf based on new data"""
    hypos = pmf.qs
    likelihood = 1/hypos
    impossible = (data > hypos)
    likelihood[impossible] = 0
    pmf *= likelihood
    pmf.normalize()

In [40]:
pmf = prior.copy()
pmf

6     0.333333
8     0.333333
12    0.333333
dtype: float64

In [41]:
update_dice(pmf, 1)
update_dice(pmf, 7)
pmf

6     0.000000
8     0.692308
12    0.307692
dtype: float64

# Exercise 3-1

In [64]:
hypos = [6, 8, 12]

In [65]:
prior = Pmf(1/3, hypos )

In [66]:
prior

6     0.333333
8     0.333333
12    0.333333
dtype: float64

In [67]:
pmf = prior.copy()

In [68]:
update_dice(pmf, 1)
update_dice(pmf, 3)
update_dice(pmf, 5)
update_dice(pmf, 7)
pmf

6     0.000000
8     0.835052
12    0.164948
dtype: float64

# Exercise 3-2

In [70]:
hypos = [4, 6, 8, 12, 20]

In [71]:
prior = Pmf(1/15, hypos)

In [74]:
qs = prior.qs
qs

array([ 4,  6,  8, 12, 20])

In [75]:
ps = [1, 2, 3, 4, 5]

In [76]:
pmf = Pmf(ps, qs)

In [77]:
pmf

4     1
6     2
8     3
12    4
20    5
dtype: int64

In [78]:
update_dice(pmf, 7)
pmf

4     0.000000
6     0.000000
8     0.391304
12    0.347826
20    0.260870
dtype: float64

# Exc 3-3

In [79]:
hypos = ['BlackWhite', 'RedGreenBlue']

In [80]:
prior = Pmf(1/2, hypos)

In [81]:
likelihood = 1/2, 1/3

In [82]:
posterior = prior * likelihood

In [83]:
posterior.normalize()
posterior

BlackWhite      0.6
RedGreenBlue    0.4
dtype: float64

In [84]:
posterior['BlackWhite'] / 2

0.30000000000000004

# Exc 3-4

In [85]:
# Solution

# The trick to this question is to notice that Elvis's twin was a brother.
# If they were identical twins, it is certain they would be the same sex.
# If they were fraternal twins, the likelihood is only 50%.

# Here's a solution using a Bayes table

import pandas as pd

table = pd.DataFrame(index=['identical', 'fraternal'])
table['prior'] = 1/3, 2/3
table['likelihood'] = 1, 1/2

table['unnorm'] = table['prior'] * table['likelihood']
prob_data = table['unnorm'].sum()

table['posterior'] = table['unnorm'] / prob_data
table

prior  likelihood    unnorm  posterior
identical  0.333333         1.0  0.333333        0.5
fraternal  0.666667         0.5  0.333333        0.5

In [86]:
# Solution

# Here's a solution using a Pmf

hypos = ['identical', 'fraternal']
prior = Pmf([1/3, 2/3], hypos)
prior

identical    0.333333
fraternal    0.666667
dtype: float64

In [87]:
# Solution

likelihood = 1, 1/2
posterior = prior * likelihood
posterior.normalize()
posterior

identical    0.5
fraternal    0.5
dtype: float64

# The Binominal Distribution